### ISSUE TITLE
Fails to detect some titles playing

### ISSUE THREAD

**Issue by vgerak** [Atelier-Shiori/malupdaterosx-cocoa#15] opened 2016-02-12 12:00 UTC
For some titles, the application does not detect that something is playing, and does not scrobble at all.
(It doesn't return wrong title, it operates like nothing at all is playing)

Reproducible with mpv on [Coalgirls]'s edition of Clannad.

**Comment by chikorita157** [comment] 2016-02-13 18:02
Not sure if it's a recognition or a detection issue. Are you using a compiled binary of mpv for OS X? Also, some filenames would help to see if it's a recognition issue or not.

**Comment by indorilftw** [comment] 2016-02-13 21:25
I think it doesn't even detect this one.
I'm not getting the "Could not find title" notification, and it detects every other show fine.

Using precompiled binary from [mpv.io](https://mpv.io/installation/).
Filename example is "Clannad 17" and below are the first lines of the `mkvinfo` command output (Notably, the "Title" property is set to "Clannad 17" as well).

```
$ mkvinfo Clannad 17.mkv
+ EBML head
|+ EBML version: 1
|+ EBML read version: 1
|+ EBML maximum ID length: 4
|+ EBML maximum size length: 8
|+ Doc type: matroska
|+ Doc type version: 2
|+ Doc type read version: 2
+ Segment, size 438070357
|+ Seek head (subentries will be skipped)
|+ EbmlVoid (size: 4013)
|+ Segment information
| + Timecode scale: 1000000
| + Muxing application: libebml v1.2.0 + libmatroska v1.1.0
| + Writing application: mkvmerge v4.5.0 ('Speed of Light') built on Feb  1 2011 02:10:32
| + Duration: 1269.810s (00:21:09.810)
| + Date: Thu Mar 10 18:24:38 2011 UTC
| + Title: Clannad 17
| + Segment UID: 0x96 0x74 0xb3 0x51 0x78 0x6b 0x94 0x46 0xa0 0x66 0xde 0xf7 0xf6 0x81 0x98 0xda
|+ Segment tracks
| + A track
|  + Track number: 1 (track ID for mkvmerge & mkvextract: 0)
|  + Track UID: 1779958421
|  + Track type: video
|  + Lacing flag: 0
|  + MinCache: 1
|  + Codec ID: V_MPEG4/ISO/AVC
|  + CodecPrivate, length 43 (h.264 profile: High @L5.0)
|  + Default duration: 41.708ms (23.976 frames/fields per second for a video track)
|  + Language: und
|  + Name: Clannad 17
|  + Video track
|   + Pixel width: 1280
|   + Pixel height: 720
|   + Display width: 1280
|   + Display height: 720
[...]
```

**Comment by chikorita157** [comment] 2016-02-13 22:01
I have check to see if its a recognition problem and its not. Here is what I get from using the filename for the Anitomy for OS X demo

`{
    episode = 17;
    episodetitle = "";
    episodetype = "";
    group = "";
    releaseversion = "";
    season = "";
    title = Clannad;
    type =     (
    );
    videosource = "";
    videoterm = "";
    year = "";
}`

After further testing, I see that it detects, but as the second season. I will probably implement string scoring to fix that in the next version.

**Comment by chikorita157** [comment] 2016-03-13 17:51
I know it's late, but I added string scoring so that the title should detect properly. It will be released sometime this week after I do some regression testing to see if there is any new bugs introduced. It shouldn't matter what player you use since MAL Updater OS X uses lsof to get the filename, unless the video player is not on the list of process names supported by the program.

**Closed** 2016-08-23 19:55 UTC
